/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/openapi": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["DocsController_getOpenApi"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/reference": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["DocsController_getReference"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/import-flows/ingress/pull": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["ImportFlowController_pullFromIngress"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/import-flows/{batchId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["ImportFlowController_getBatch"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/import-flows/{batchId}/match": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["ImportFlowController_runMatching"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/import-flows/{batchId}/review": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["ImportFlowController_submitReview"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/import-flows/{batchId}/commit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["ImportFlowController_commitBatch"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ReasoningCandidateDto: {
      label: string;
      confidence: number;
      notes: string;
    };
    ImportDocumentResponseDto: {
      id: string;
      title: string;
      url?: Record<string, never> | null;
    };
    ImportItemResponseDto: {
      id: string;
      batchId: string;
      ingressKey: string;
      sku: string;
      vendor: string;
      quantity: number;
      rawPayload: {
        [key: string]: unknown;
      };
      normalizedName?: Record<string, never> | null;
      category?: Record<string, never> | null;
      confidence?: Record<string, never> | null;
      reasoning?: Record<string, never> | null;
      candidates: components["schemas"]["ReasoningCandidateDto"][];
      /** @enum {string} */
      technicianDecision: "pending" | "confirmed" | "edited" | "needs-doc";
      technicianNotes?: Record<string, never> | null;
      documents: components["schemas"]["ImportDocumentResponseDto"][];
      createdAt: string;
      updatedAt: string;
    };
    ImportBatchResponseDto: {
      id: string;
      /** @enum {string} */
      source: "ingress-controller";
      sourceLabel: string;
      /** @enum {string} */
      status: "ingested" | "matched" | "reviewed" | "committed";
      createdAt: string;
      updatedAt: string;
      items: components["schemas"]["ImportItemResponseDto"][];
    };
    ImportDocumentDto: {
      title: string;
      url?: string;
    };
    ImportItemReviewDto: {
      /** Format: uuid */
      itemId: string;
      /** @enum {string} */
      technicianDecision: "confirmed" | "edited" | "needs-doc";
      technicianNotes?: string;
      normalizedName?: string;
      category?: string;
      documents: components["schemas"]["ImportDocumentDto"][];
    };
    ReviewImportBatchDto: {
      items: components["schemas"]["ImportItemReviewDto"][];
    };
    ComponentCatalogEntryResponseDto: {
      id: string;
      importItemId: string;
      sku: string;
      vendor: string;
      normalizedName: string;
      category: string;
      confidence: number;
      /** @enum {string} */
      technicianDecision: "pending" | "confirmed" | "edited" | "needs-doc";
      documentation: components["schemas"]["ImportDocumentResponseDto"][];
      createdAt: string;
    };
    CommitImportBatchResponseDto: {
      batch: components["schemas"]["ImportBatchResponseDto"];
      catalogEntries: components["schemas"]["ComponentCatalogEntryResponseDto"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  DocsController_getOpenApi: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  DocsController_getReference: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ImportFlowController_pullFromIngress: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportBatchResponseDto"];
        };
      };
    };
  };
  ImportFlowController_getBatch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        batchId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportBatchResponseDto"];
        };
      };
    };
  };
  ImportFlowController_runMatching: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        batchId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportBatchResponseDto"];
        };
      };
    };
  };
  ImportFlowController_submitReview: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        batchId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReviewImportBatchDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportBatchResponseDto"];
        };
      };
    };
  };
  ImportFlowController_commitBatch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        batchId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommitImportBatchResponseDto"];
        };
      };
    };
  };
}
