import { ThemeProvider } from '@/components/theme-provider';
import './global.css';

export const metadata = {
  title: 'Project ATLAS',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem
                    disableTransitionOnChange
                  >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
