import type { Asset, DependencyEdge, FloorData, FloorId, Zone } from "./mapTypes";

// Facility coordinate space: 200 × 100 units per floor.
// All three floors share the same coordinate space but have different zone/asset layouts.

// ─── Floor B — Main Data Hall (Ground Level) ─────────────────────────────────
// Layout: Electrical (left), Rack rows (center), Cooling (right), Network (bottom)

const FLOOR_B_ZONES: Zone[] = [
  {
    id: "hall-b",
    name: "Hall B",
    type: "hall",
    polygon: [
      [0, 0],
      [200, 0],
      [200, 100],
      [0, 100],
      [0, 0],
    ],
    metadata: { sqft: 20000 },
  },
  {
    id: "electrical-zone",
    name: "Electrical Zone",
    type: "electrical",
    polygon: [
      [2, 10],
      [36, 10],
      [36, 90],
      [2, 90],
      [2, 10],
    ],
    metadata: { circuits: 48 },
  },
  {
    id: "row-c",
    name: "Row C",
    type: "row",
    polygon: [
      [40, 4],
      [158, 4],
      [158, 45],
      [40, 45],
      [40, 4],
    ],
    metadata: { racks: 8 },
  },
  {
    id: "cold-aisle",
    name: "Cold Aisle",
    type: "corridor",
    polygon: [
      [40, 46],
      [158, 46],
      [158, 54],
      [40, 54],
      [40, 46],
    ],
    metadata: {},
  },
  {
    id: "row-d",
    name: "Row D",
    type: "row",
    polygon: [
      [40, 55],
      [158, 55],
      [158, 96],
      [40, 96],
      [40, 55],
    ],
    metadata: { racks: 8 },
  },
  {
    id: "service-corridor",
    name: "Service Corridor",
    type: "corridor",
    polygon: [
      [160, 4],
      [164, 4],
      [164, 96],
      [160, 96],
      [160, 4],
    ],
    metadata: {},
  },
  {
    id: "cooling-zone",
    name: "Cooling Zone",
    type: "cooling",
    polygon: [
      [166, 10],
      [198, 10],
      [198, 90],
      [166, 90],
      [166, 10],
    ],
    metadata: { units: 2 },
  },
  {
    id: "network-zone",
    name: "Network Zone",
    type: "network",
    polygon: [
      [55, 87],
      [135, 87],
      [135, 98],
      [55, 98],
      [55, 87],
    ],
    metadata: {},
  },
];

// Rack X positions for Row C and D (8 racks, x from 48 to 148)
const RACK_XS = [48, 62, 76, 90, 104, 118, 132, 146] as const;

const FLOOR_B_ASSETS: Asset[] = [
  // ── Electrical Zone ──────────────────────────────────────────────────────
  {
    id: "ups-01",
    name: "UPS-01",
    type: "ups",
    status: "normal",
    coordinates: [14, 35],
    zoneId: "electrical-zone",
    floorId: "floor-b",
    criticality: "critical",
    metadata: { model: "Eaton 9PX", capacity_kva: 20, battery_runtime: "12 min", load_pct: 67 },
  },
  {
    id: "pdu-01",
    name: "PDU-01",
    type: "pdu",
    status: "normal",
    coordinates: [27, 22],
    zoneId: "electrical-zone",
    floorId: "floor-b",
    criticality: "high",
    metadata: { model: "Raritan PX3", circuits: 24, load_amps: 32 },
  },
  {
    id: "pdu-02",
    name: "PDU-02",
    type: "pdu",
    status: "normal",
    coordinates: [27, 50],
    zoneId: "electrical-zone",
    floorId: "floor-b",
    criticality: "high",
    metadata: { model: "Raritan PX3", circuits: 24, load_amps: 28 },
  },
  {
    id: "sensor-elec-01",
    name: "Sensor-E1",
    type: "sensor",
    status: "normal",
    coordinates: [20, 80],
    zoneId: "electrical-zone",
    floorId: "floor-b",
    criticality: "low",
    metadata: { metric: "voltage", unit: "V", value: 208 },
  },

  // ── Cooling Zone ─────────────────────────────────────────────────────────
  {
    id: "crac-07",
    name: "CRAC-07",
    type: "crac",
    status: "normal",
    coordinates: [181, 32],
    zoneId: "cooling-zone",
    floorId: "floor-b",
    criticality: "critical",
    metadata: {
      model: "Stulz CyberAir 3",
      capacity_kw: 45,
      airflow_cfm: 5800,
      supply_temp: "16°C",
    },
  },
  {
    id: "crac-08",
    name: "CRAC-08",
    type: "crac",
    status: "normal",
    coordinates: [181, 66],
    zoneId: "cooling-zone",
    floorId: "floor-b",
    criticality: "critical",
    metadata: {
      model: "Stulz CyberAir 3",
      capacity_kw: 45,
      airflow_cfm: 5800,
      supply_temp: "16°C",
    },
  },
  {
    id: "sensor-cool-01",
    name: "Sensor-CL1",
    type: "sensor",
    status: "normal",
    coordinates: [172, 15],
    zoneId: "cooling-zone",
    floorId: "floor-b",
    criticality: "medium",
    metadata: { metric: "temp", unit: "°C", value: 16.2 },
  },

  // ── Row C — 8 racks ──────────────────────────────────────────────────────
  {
    id: "switch-01",
    name: "Switch-01",
    type: "switch",
    status: "normal",
    coordinates: [48, 38],
    zoneId: "row-c",
    floorId: "floor-b",
    criticality: "high",
    metadata: { model: "Cisco Nexus 9348", ports: 48, speed_gbps: 25 },
  },
  {
    id: "sensor-c1",
    name: "Sensor-C1",
    type: "sensor",
    status: "normal",
    coordinates: [82, 8],
    zoneId: "row-c",
    floorId: "floor-b",
    criticality: "medium",
    metadata: { metric: "temp", unit: "°C", value: 21.4 },
  },
  {
    id: "sensor-c2",
    name: "Sensor-C2",
    type: "sensor",
    status: "normal",
    coordinates: [128, 8],
    zoneId: "row-c",
    floorId: "floor-b",
    criticality: "medium",
    metadata: { metric: "temp", unit: "°C", value: 22.1 },
  },
  ...RACK_XS.map((x, i) => ({
    id: `rack-c${12 + i}`,
    name: `Rack-C${12 + i}`,
    type: "rack" as const,
    status: "normal" as const,
    coordinates: [x, 25] as [number, number],
    zoneId: "row-c",
    floorId: "floor-b" as FloorId,
    criticality: "high" as const,
    metadata: { u_total: 42, u_used: 38 - i, power_kw: 12.4 - i * 0.3 },
  })),

  // ── Row D — 8 racks ──────────────────────────────────────────────────────
  {
    id: "switch-02",
    name: "Switch-02",
    type: "switch",
    status: "normal",
    coordinates: [48, 62],
    zoneId: "row-d",
    floorId: "floor-b",
    criticality: "high",
    metadata: { model: "Cisco Nexus 9348", ports: 48, speed_gbps: 25 },
  },
  {
    id: "sensor-d1",
    name: "Sensor-D1",
    type: "sensor",
    status: "normal",
    coordinates: [82, 92],
    zoneId: "row-d",
    floorId: "floor-b",
    criticality: "medium",
    metadata: { metric: "temp", unit: "°C", value: 20.8 },
  },
  {
    id: "sensor-d2",
    name: "Sensor-D2",
    type: "sensor",
    status: "normal",
    coordinates: [128, 92],
    zoneId: "row-d",
    floorId: "floor-b",
    criticality: "medium",
    metadata: { metric: "temp", unit: "°C", value: 21.2 },
  },
  ...RACK_XS.map((x, i) => ({
    id: `rack-d0${i + 1}`,
    name: `Rack-D0${i + 1}`,
    type: "rack" as const,
    status: "normal" as const,
    coordinates: [x, 75] as [number, number],
    zoneId: "row-d",
    floorId: "floor-b" as FloorId,
    criticality: "high" as const,
    metadata: { u_total: 42, u_used: 40 - i, power_kw: 14.1 - i * 0.4 },
  })),

  // ── Network Zone ─────────────────────────────────────────────────────────
  {
    id: "sensor-net-01",
    name: "Sensor-N1",
    type: "sensor",
    status: "normal",
    coordinates: [90, 92],
    zoneId: "network-zone",
    floorId: "floor-b",
    criticality: "low",
    metadata: { metric: "latency", unit: "ms", value: 0.4 },
  },
];

const FLOOR_B_EDGES: DependencyEdge[] = [
  // UPS-01 → PDU-01 / PDU-02
  {
    id: "ups01-pdu01",
    sourceAssetId: "ups-01",
    targetAssetId: "pdu-01",
    type: "FEEDS",
    resource: "power",
    criticality: "critical",
    activeInIncident: false,
  },
  {
    id: "ups01-pdu02",
    sourceAssetId: "ups-01",
    targetAssetId: "pdu-02",
    type: "FEEDS",
    resource: "power",
    criticality: "critical",
    activeInIncident: false,
  },

  // PDU-01 → Row C racks
  ...RACK_XS.map((_, i) => ({
    id: `pdu01-rack-c${12 + i}`,
    sourceAssetId: "pdu-01",
    targetAssetId: `rack-c${12 + i}`,
    type: "FEEDS" as const,
    resource: "power" as const,
    criticality: "high" as const,
    activeInIncident: false,
  })),

  // PDU-02 → Row D racks
  ...RACK_XS.map((_, i) => ({
    id: `pdu02-rack-d0${i + 1}`,
    sourceAssetId: "pdu-02",
    targetAssetId: `rack-d0${i + 1}`,
    type: "FEEDS" as const,
    resource: "power" as const,
    criticality: "high" as const,
    activeInIncident: false,
  })),

  // CRAC-07 → Row C racks (cooling)
  ...RACK_XS.map((_, i) => ({
    id: `crac07-rack-c${12 + i}`,
    sourceAssetId: "crac-07",
    targetAssetId: `rack-c${12 + i}`,
    type: "FEEDS" as const,
    resource: "cooling" as const,
    criticality: "critical" as const,
    minutesToImpact: 14 + i * 2,
    activeInIncident: false,
  })),

  // CRAC-08 → Row D racks (cooling)
  ...RACK_XS.map((_, i) => ({
    id: `crac08-rack-d0${i + 1}`,
    sourceAssetId: "crac-08",
    targetAssetId: `rack-d0${i + 1}`,
    type: "FEEDS" as const,
    resource: "cooling" as const,
    criticality: "critical" as const,
    minutesToImpact: 18 + i * 2,
    activeInIncident: false,
  })),

  // Switch-01 → Row C racks (network)
  ...RACK_XS.map((_, i) => ({
    id: `sw01-rack-c${12 + i}`,
    sourceAssetId: "switch-01",
    targetAssetId: `rack-c${12 + i}`,
    type: "CONNECTED_TO" as const,
    resource: "network" as const,
    criticality: "high" as const,
    activeInIncident: false,
  })),

  // Switch-02 → Row D racks (network)
  ...RACK_XS.map((_, i) => ({
    id: `sw02-rack-d0${i + 1}`,
    sourceAssetId: "switch-02",
    targetAssetId: `rack-d0${i + 1}`,
    type: "CONNECTED_TO" as const,
    resource: "network" as const,
    criticality: "high" as const,
    activeInIncident: false,
  })),

  // Sensor dependencies
  {
    id: "sensor-c1-crac07",
    sourceAssetId: "sensor-c1",
    targetAssetId: "crac-07",
    type: "DEPENDS_ON",
    resource: "dependency",
    criticality: "medium",
    activeInIncident: false,
  },
  {
    id: "sensor-c2-crac07",
    sourceAssetId: "sensor-c2",
    targetAssetId: "crac-07",
    type: "DEPENDS_ON",
    resource: "dependency",
    criticality: "medium",
    activeInIncident: false,
  },
];

// ─── Floor A — Network Ops / Secondary Compute (Upper Level) ──────────────────

const FLOOR_A_ZONES: Zone[] = [
  {
    id: "hall-a",
    name: "Hall A",
    type: "hall",
    polygon: [
      [0, 0],
      [200, 0],
      [200, 100],
      [0, 100],
      [0, 0],
    ],
    metadata: { sqft: 12000 },
  },
  {
    id: "noc-zone",
    name: "NOC",
    type: "noc",
    polygon: [
      [2, 5],
      [80, 5],
      [80, 55],
      [2, 55],
      [2, 5],
    ],
    metadata: { stations: 6 },
  },
  {
    id: "secondary-compute",
    name: "Secondary Compute",
    type: "row",
    polygon: [
      [85, 5],
      [198, 5],
      [198, 55],
      [85, 55],
      [85, 5],
    ],
    metadata: { racks: 7 },
  },
  {
    id: "ups-room-a",
    name: "UPS Room A",
    type: "ups_room",
    polygon: [
      [2, 60],
      [80, 60],
      [80, 95],
      [2, 95],
      [2, 60],
    ],
    metadata: {},
  },
  {
    id: "patch-bay",
    name: "Patch Bay",
    type: "patch_bay",
    polygon: [
      [85, 60],
      [198, 60],
      [198, 95],
      [85, 95],
      [85, 60],
    ],
    metadata: {},
  },
];

const FLOOR_A_ASSETS: Asset[] = [
  // NOC Zone
  {
    id: "fw-01",
    name: "FW-01",
    type: "firewall",
    status: "normal",
    coordinates: [18, 20],
    zoneId: "noc-zone",
    floorId: "floor-a",
    criticality: "critical",
    metadata: { model: "Palo Alto PA-5260", throughput_gbps: 70, sessions: 64000000 },
  },
  {
    id: "fw-02",
    name: "FW-02",
    type: "firewall",
    status: "normal",
    coordinates: [18, 42],
    zoneId: "noc-zone",
    floorId: "floor-a",
    criticality: "critical",
    metadata: { model: "Palo Alto PA-5260", throughput_gbps: 70, sessions: 64000000 },
  },
  {
    id: "core-sw-01",
    name: "Core-SW-01",
    type: "switch",
    status: "normal",
    coordinates: [50, 20],
    zoneId: "noc-zone",
    floorId: "floor-a",
    criticality: "critical",
    metadata: { model: "Arista 7368X4", ports: 64, speed_gbps: 400 },
  },
  {
    id: "core-sw-02",
    name: "Core-SW-02",
    type: "switch",
    status: "normal",
    coordinates: [50, 42],
    zoneId: "noc-zone",
    floorId: "floor-a",
    criticality: "critical",
    metadata: { model: "Arista 7368X4", ports: 64, speed_gbps: 400 },
  },
  {
    id: "sensor-noc-01",
    name: "Sensor-N01",
    type: "sensor",
    status: "normal",
    coordinates: [70, 10],
    zoneId: "noc-zone",
    floorId: "floor-a",
    criticality: "low",
    metadata: { metric: "temp", unit: "°C", value: 20.1 },
  },

  // Secondary Compute Zone
  {
    id: "pdu-a01",
    name: "PDU-A01",
    type: "pdu",
    status: "normal",
    coordinates: [90, 28],
    zoneId: "secondary-compute",
    floorId: "floor-a",
    criticality: "high",
    metadata: { circuits: 24, load_pct: 58 },
  },
  {
    id: "sw-a01",
    name: "SW-A01",
    type: "switch",
    status: "normal",
    coordinates: [90, 48],
    zoneId: "secondary-compute",
    floorId: "floor-a",
    criticality: "high",
    metadata: { model: "Arista 7050SX3", ports: 48, speed_gbps: 100 },
  },
  {
    id: "rack-a01",
    name: "Rack-A01",
    type: "rack",
    status: "normal",
    coordinates: [110, 20],
    zoneId: "secondary-compute",
    floorId: "floor-a",
    criticality: "high",
    metadata: { u_used: 36, power_kw: 10.2 },
  },
  {
    id: "rack-a02",
    name: "Rack-A02",
    type: "rack",
    status: "normal",
    coordinates: [128, 20],
    zoneId: "secondary-compute",
    floorId: "floor-a",
    criticality: "high",
    metadata: { u_used: 34, power_kw: 9.8 },
  },
  {
    id: "rack-a03",
    name: "Rack-A03",
    type: "rack",
    status: "normal",
    coordinates: [146, 20],
    zoneId: "secondary-compute",
    floorId: "floor-a",
    criticality: "medium",
    metadata: { u_used: 28, power_kw: 8.1 },
  },
  {
    id: "rack-a04",
    name: "Rack-A04",
    type: "rack",
    status: "normal",
    coordinates: [164, 20],
    zoneId: "secondary-compute",
    floorId: "floor-a",
    criticality: "medium",
    metadata: { u_used: 24, power_kw: 7.4 },
  },
  {
    id: "rack-a05",
    name: "Rack-A05",
    type: "rack",
    status: "normal",
    coordinates: [182, 20],
    zoneId: "secondary-compute",
    floorId: "floor-a",
    criticality: "medium",
    metadata: { u_used: 20, power_kw: 6.2 },
  },
  {
    id: "rack-a06",
    name: "Rack-A06",
    type: "rack",
    status: "normal",
    coordinates: [128, 45],
    zoneId: "secondary-compute",
    floorId: "floor-a",
    criticality: "medium",
    metadata: { u_used: 30, power_kw: 8.8 },
  },
  {
    id: "rack-a07",
    name: "Rack-A07",
    type: "rack",
    status: "normal",
    coordinates: [164, 45],
    zoneId: "secondary-compute",
    floorId: "floor-a",
    criticality: "low",
    metadata: { u_used: 18, power_kw: 5.5 },
  },
  {
    id: "sensor-sc-01",
    name: "Sensor-SC1",
    type: "sensor",
    status: "normal",
    coordinates: [145, 9],
    zoneId: "secondary-compute",
    floorId: "floor-a",
    criticality: "medium",
    metadata: { metric: "temp", unit: "°C", value: 22.8 },
  },

  // UPS Room A
  {
    id: "ups-02",
    name: "UPS-02",
    type: "ups",
    status: "normal",
    coordinates: [20, 76],
    zoneId: "ups-room-a",
    floorId: "floor-a",
    criticality: "high",
    metadata: { model: "APC Symmetra LX", capacity_kva: 16, load_pct: 52 },
  },
  {
    id: "battery-a01",
    name: "Battery-A01",
    type: "battery",
    status: "normal",
    coordinates: [50, 76],
    zoneId: "ups-room-a",
    floorId: "floor-a",
    criticality: "high",
    metadata: { model: "VRLA Array", capacity_kwh: 24, soh_pct: 94 },
  },
  {
    id: "sensor-ups-a01",
    name: "Sensor-UA1",
    type: "sensor",
    status: "normal",
    coordinates: [68, 65],
    zoneId: "ups-room-a",
    floorId: "floor-a",
    criticality: "low",
    metadata: { metric: "temp", unit: "°C", value: 23.5 },
  },

  // Patch Bay
  {
    id: "patch-01",
    name: "Patch-01",
    type: "patch_panel",
    status: "normal",
    coordinates: [110, 75],
    zoneId: "patch-bay",
    floorId: "floor-a",
    criticality: "medium",
    metadata: { ports: 96, patch_cords: 88 },
  },
  {
    id: "patch-02",
    name: "Patch-02",
    type: "patch_panel",
    status: "normal",
    coordinates: [150, 75],
    zoneId: "patch-bay",
    floorId: "floor-a",
    criticality: "medium",
    metadata: { ports: 96, patch_cords: 72 },
  },
  {
    id: "patch-03",
    name: "Patch-03",
    type: "patch_panel",
    status: "normal",
    coordinates: [185, 75],
    zoneId: "patch-bay",
    floorId: "floor-a",
    criticality: "low",
    metadata: { ports: 48, patch_cords: 36 },
  },
];

const FLOOR_A_EDGES: DependencyEdge[] = [
  // UPS-02 → PDU-A01
  {
    id: "ups02-pdu-a01",
    sourceAssetId: "ups-02",
    targetAssetId: "pdu-a01",
    type: "FEEDS",
    resource: "power",
    criticality: "high",
    activeInIncident: false,
  },
  // PDU-A01 → racks
  {
    id: "pdu-a01-rack-a01",
    sourceAssetId: "pdu-a01",
    targetAssetId: "rack-a01",
    type: "FEEDS",
    resource: "power",
    criticality: "high",
    activeInIncident: false,
  },
  {
    id: "pdu-a01-rack-a02",
    sourceAssetId: "pdu-a01",
    targetAssetId: "rack-a02",
    type: "FEEDS",
    resource: "power",
    criticality: "high",
    activeInIncident: false,
  },
  {
    id: "pdu-a01-rack-a03",
    sourceAssetId: "pdu-a01",
    targetAssetId: "rack-a03",
    type: "FEEDS",
    resource: "power",
    criticality: "medium",
    activeInIncident: false,
  },
  {
    id: "pdu-a01-rack-a04",
    sourceAssetId: "pdu-a01",
    targetAssetId: "rack-a04",
    type: "FEEDS",
    resource: "power",
    criticality: "medium",
    activeInIncident: false,
  },
  {
    id: "pdu-a01-rack-a05",
    sourceAssetId: "pdu-a01",
    targetAssetId: "rack-a05",
    type: "FEEDS",
    resource: "power",
    criticality: "medium",
    activeInIncident: false,
  },
  {
    id: "pdu-a01-rack-a06",
    sourceAssetId: "pdu-a01",
    targetAssetId: "rack-a06",
    type: "FEEDS",
    resource: "power",
    criticality: "medium",
    activeInIncident: false,
  },
  {
    id: "pdu-a01-rack-a07",
    sourceAssetId: "pdu-a01",
    targetAssetId: "rack-a07",
    type: "FEEDS",
    resource: "power",
    criticality: "low",
    activeInIncident: false,
  },
  // Core switches ↔ firewalls (network)
  {
    id: "core-sw01-fw01",
    sourceAssetId: "core-sw-01",
    targetAssetId: "fw-01",
    type: "CONNECTED_TO",
    resource: "network",
    criticality: "critical",
    activeInIncident: false,
  },
  {
    id: "core-sw01-fw02",
    sourceAssetId: "core-sw-01",
    targetAssetId: "fw-02",
    type: "CONNECTED_TO",
    resource: "network",
    criticality: "critical",
    activeInIncident: false,
  },
  {
    id: "core-sw02-fw01",
    sourceAssetId: "core-sw-02",
    targetAssetId: "fw-01",
    type: "CONNECTED_TO",
    resource: "network",
    criticality: "critical",
    activeInIncident: false,
  },
  // SW-A01 → racks (network)
  {
    id: "sw-a01-rack-a01",
    sourceAssetId: "sw-a01",
    targetAssetId: "rack-a01",
    type: "CONNECTED_TO",
    resource: "network",
    criticality: "high",
    activeInIncident: false,
  },
  {
    id: "sw-a01-rack-a02",
    sourceAssetId: "sw-a01",
    targetAssetId: "rack-a02",
    type: "CONNECTED_TO",
    resource: "network",
    criticality: "high",
    activeInIncident: false,
  },
  {
    id: "sw-a01-rack-a03",
    sourceAssetId: "sw-a01",
    targetAssetId: "rack-a03",
    type: "CONNECTED_TO",
    resource: "network",
    criticality: "medium",
    activeInIncident: false,
  },
  // Battery → UPS dependency
  {
    id: "battery-a01-ups02",
    sourceAssetId: "battery-a01",
    targetAssetId: "ups-02",
    type: "DEPENDS_ON",
    resource: "dependency",
    criticality: "high",
    activeInIncident: false,
  },
];

// ─── Floor C — Mechanical / Basement ─────────────────────────────────────────

const FLOOR_C_ZONES: Zone[] = [
  {
    id: "hall-c",
    name: "Hall C",
    type: "hall",
    polygon: [
      [0, 0],
      [200, 0],
      [200, 100],
      [0, 100],
      [0, 0],
    ],
    metadata: { sqft: 14000 },
  },
  {
    id: "generator-room",
    name: "Generator Room",
    type: "generator",
    polygon: [
      [2, 5],
      [80, 5],
      [80, 52],
      [2, 52],
      [2, 5],
    ],
    metadata: { units: 2 },
  },
  {
    id: "chiller-plant",
    name: "Chiller Plant",
    type: "chiller_plant",
    polygon: [
      [85, 5],
      [198, 5],
      [198, 52],
      [85, 52],
      [85, 5],
    ],
    metadata: { units: 3 },
  },
  {
    id: "battery-room",
    name: "Battery Room",
    type: "battery_room",
    polygon: [
      [2, 57],
      [80, 57],
      [80, 95],
      [2, 95],
      [2, 57],
    ],
    metadata: {},
  },
  {
    id: "main-switchgear",
    name: "Main Switchgear",
    type: "switchgear",
    polygon: [
      [85, 57],
      [198, 57],
      [198, 95],
      [85, 95],
      [85, 57],
    ],
    metadata: {},
  },
];

const FLOOR_C_ASSETS: Asset[] = [
  // Generator Room
  {
    id: "gen-01",
    name: "GEN-01",
    type: "generator",
    status: "normal",
    coordinates: [22, 25],
    zoneId: "generator-room",
    floorId: "floor-c",
    criticality: "critical",
    metadata: { model: "Cummins C1100D5", capacity_kw: 1100, fuel_pct: 88, runtime_hrs: 72 },
  },
  {
    id: "gen-02",
    name: "GEN-02",
    type: "generator",
    status: "normal",
    coordinates: [58, 25],
    zoneId: "generator-room",
    floorId: "floor-c",
    criticality: "critical",
    metadata: { model: "Cummins C1100D5", capacity_kw: 1100, fuel_pct: 91, runtime_hrs: 72 },
  },
  {
    id: "sensor-gen-01",
    name: "Sensor-G1",
    type: "sensor",
    status: "normal",
    coordinates: [38, 10],
    zoneId: "generator-room",
    floorId: "floor-c",
    criticality: "medium",
    metadata: { metric: "exhaust_temp", unit: "°C", value: 142 },
  },
  {
    id: "sensor-gen-02",
    name: "Sensor-G2",
    type: "sensor",
    status: "normal",
    coordinates: [65, 44],
    zoneId: "generator-room",
    floorId: "floor-c",
    criticality: "low",
    metadata: { metric: "fuel_level", unit: "%", value: 88 },
  },

  // Chiller Plant
  {
    id: "chw-01",
    name: "CHW-01",
    type: "chiller",
    status: "normal",
    coordinates: [108, 22],
    zoneId: "chiller-plant",
    floorId: "floor-c",
    criticality: "critical",
    metadata: { model: "Trane CenTraVac", capacity_ton: 400, cop: 6.1, supply_temp: "7°C" },
  },
  {
    id: "chw-02",
    name: "CHW-02",
    type: "chiller",
    status: "normal",
    coordinates: [152, 22],
    zoneId: "chiller-plant",
    floorId: "floor-c",
    criticality: "critical",
    metadata: { model: "Trane CenTraVac", capacity_ton: 400, cop: 6.1, supply_temp: "7°C" },
  },
  {
    id: "chw-03",
    name: "CHW-03",
    type: "chiller",
    status: "normal",
    coordinates: [108, 43],
    zoneId: "chiller-plant",
    floorId: "floor-c",
    criticality: "high",
    metadata: { model: "Carrier AquaEdge", capacity_ton: 300, cop: 5.8, supply_temp: "7°C" },
  },
  {
    id: "sensor-chw-01",
    name: "Sensor-CW1",
    type: "sensor",
    status: "normal",
    coordinates: [190, 12],
    zoneId: "chiller-plant",
    floorId: "floor-c",
    criticality: "medium",
    metadata: { metric: "chw_supply_temp", unit: "°C", value: 7.2 },
  },

  // Battery Room
  {
    id: "battery-c01",
    name: "Battery-C01",
    type: "battery",
    status: "normal",
    coordinates: [18, 73],
    zoneId: "battery-room",
    floorId: "floor-c",
    criticality: "high",
    metadata: { model: "EnerSys DataSafe", capacity_kwh: 120, soh_pct: 97, cells: 480 },
  },
  {
    id: "battery-c02",
    name: "Battery-C02",
    type: "battery",
    status: "normal",
    coordinates: [52, 73],
    zoneId: "battery-room",
    floorId: "floor-c",
    criticality: "high",
    metadata: { model: "EnerSys DataSafe", capacity_kwh: 120, soh_pct: 95, cells: 480 },
  },
  {
    id: "sensor-bat-01",
    name: "Sensor-B1",
    type: "sensor",
    status: "normal",
    coordinates: [68, 62],
    zoneId: "battery-room",
    floorId: "floor-c",
    criticality: "medium",
    metadata: { metric: "temp", unit: "°C", value: 21.4 },
  },

  // Main Switchgear
  {
    id: "main-swg-01",
    name: "Main-SWG-01",
    type: "switchgear",
    status: "normal",
    coordinates: [115, 73],
    zoneId: "main-switchgear",
    floorId: "floor-c",
    criticality: "critical",
    metadata: { model: "ABB MNS", voltage_kv: 0.4, rated_amps: 4000, breakers: 24 },
  },
  {
    id: "ats-01",
    name: "ATS-01",
    type: "switchgear",
    status: "normal",
    coordinates: [160, 73],
    zoneId: "main-switchgear",
    floorId: "floor-c",
    criticality: "critical",
    metadata: { model: "Asco 7000 Series", transfer_time_ms: 100, rated_amps: 3000 },
  },
  {
    id: "sensor-swg-01",
    name: "Sensor-SWG1",
    type: "sensor",
    status: "normal",
    coordinates: [188, 88],
    zoneId: "main-switchgear",
    floorId: "floor-c",
    criticality: "medium",
    metadata: { metric: "phase_current_a", unit: "A", value: 1840 },
  },
];

const FLOOR_C_EDGES: DependencyEdge[] = [
  // Generators → Main Switchgear
  {
    id: "gen01-main-swg01",
    sourceAssetId: "gen-01",
    targetAssetId: "main-swg-01",
    type: "FEEDS",
    resource: "power",
    criticality: "critical",
    activeInIncident: false,
  },
  {
    id: "gen02-main-swg01",
    sourceAssetId: "gen-02",
    targetAssetId: "main-swg-01",
    type: "FEEDS",
    resource: "power",
    criticality: "critical",
    activeInIncident: false,
  },
  // Main SWG → ATS
  {
    id: "main-swg01-ats01",
    sourceAssetId: "main-swg-01",
    targetAssetId: "ats-01",
    type: "FEEDS",
    resource: "power",
    criticality: "critical",
    activeInIncident: false,
  },
  // Batteries → Main SWG (backup)
  {
    id: "bat-c01-main-swg01",
    sourceAssetId: "battery-c01",
    targetAssetId: "main-swg-01",
    type: "FEEDS",
    resource: "power",
    criticality: "high",
    activeInIncident: false,
  },
  {
    id: "bat-c02-main-swg01",
    sourceAssetId: "battery-c02",
    targetAssetId: "main-swg-01",
    type: "FEEDS",
    resource: "power",
    criticality: "high",
    activeInIncident: false,
  },
  // Chillers depend on each other (redundancy)
  {
    id: "chw01-chw03",
    sourceAssetId: "chw-01",
    targetAssetId: "chw-03",
    type: "DEPENDS_ON",
    resource: "dependency",
    criticality: "medium",
    activeInIncident: false,
  },
  {
    id: "chw02-chw03",
    sourceAssetId: "chw-02",
    targetAssetId: "chw-03",
    type: "DEPENDS_ON",
    resource: "dependency",
    criticality: "medium",
    activeInIncident: false,
  },
  // Gen sensor deps
  {
    id: "sensor-gen01-gen01",
    sourceAssetId: "sensor-gen-01",
    targetAssetId: "gen-01",
    type: "DEPENDS_ON",
    resource: "dependency",
    criticality: "low",
    activeInIncident: false,
  },
  {
    id: "sensor-gen02-gen02",
    sourceAssetId: "sensor-gen-02",
    targetAssetId: "gen-02",
    type: "DEPENDS_ON",
    resource: "dependency",
    criticality: "low",
    activeInIncident: false,
  },
];

// ─── Floor registry ───────────────────────────────────────────────────────────

export const FLOORS: Record<FloorId, FloorData> = {
  "floor-b": { id: "floor-b", zones: FLOOR_B_ZONES, assets: FLOOR_B_ASSETS, edges: FLOOR_B_EDGES },
  "floor-a": { id: "floor-a", zones: FLOOR_A_ZONES, assets: FLOOR_A_ASSETS, edges: FLOOR_A_EDGES },
  "floor-c": { id: "floor-c", zones: FLOOR_C_ZONES, assets: FLOOR_C_ASSETS, edges: FLOOR_C_EDGES },
};

// ─── Incident definition (Floor B — CRAC-07 failure cascade) ─────────────────

export interface IncidentStep {
  delayMs: number;
  assetId: string;
  status: "warning" | "critical";
  edgeIds: string[];
  message: string;
  minutesToImpact?: number;
}

export const CRAC07_INCIDENT: IncidentStep[] = [
  {
    delayMs: 0,
    assetId: "crac-07",
    status: "critical",
    edgeIds: [],
    message: "CRAC-07 compressor failure — thermal output collapsed to 0%",
  },
  {
    delayMs: 400,
    assetId: "rack-c12",
    status: "warning",
    edgeIds: ["crac07-rack-c12"],
    message: "Rack-C12 inlet temp rising — cooling loss T+14 min",
    minutesToImpact: 14,
  },
  {
    delayMs: 700,
    assetId: "rack-c13",
    status: "warning",
    edgeIds: ["crac07-rack-c13"],
    message: "Rack-C13 thermal anomaly — T+16 min to threshold",
    minutesToImpact: 16,
  },
  {
    delayMs: 1000,
    assetId: "sensor-c1",
    status: "warning",
    edgeIds: [],
    message: "Sensor-C1 flagged — Row C inlet temp exceeds 27°C",
  },
  {
    delayMs: 1200,
    assetId: "rack-c14",
    status: "warning",
    edgeIds: ["crac07-rack-c14"],
    message: "Rack-C14 entering thermal risk window — T+21 min",
    minutesToImpact: 21,
  },
  {
    delayMs: 1500,
    assetId: "rack-c15",
    status: "warning",
    edgeIds: ["crac07-rack-c15"],
    message: "Rack-C15 elevated temperature — T+24 min",
    minutesToImpact: 24,
  },
  {
    delayMs: 1900,
    assetId: "rack-c16",
    status: "warning",
    edgeIds: ["crac07-rack-c16"],
    message: "Rack-C16 warning — T+28 min",
    minutesToImpact: 28,
  },
  {
    delayMs: 2200,
    assetId: "rack-c14",
    status: "critical",
    edgeIds: ["crac07-rack-c14"],
    message: "Rack-C14 CRITICAL — thermal throttle imminent",
    minutesToImpact: 21,
  },
  {
    delayMs: 2500,
    assetId: "rack-c15",
    status: "critical",
    edgeIds: ["crac07-rack-c15"],
    message: "Rack-C15 CRITICAL — emergency shutdown risk T+29 min",
    minutesToImpact: 29,
  },
  {
    delayMs: 2800,
    assetId: "rack-c17",
    status: "warning",
    edgeIds: ["crac07-rack-c17"],
    message: "Rack-C17 elevated — monitoring",
    minutesToImpact: 42,
  },
  {
    delayMs: 3100,
    assetId: "rack-c18",
    status: "warning",
    edgeIds: ["crac07-rack-c18"],
    message: "Rack-C18 elevated — monitoring",
    minutesToImpact: 47,
  },
  {
    delayMs: 3400,
    assetId: "sensor-c2",
    status: "warning",
    edgeIds: [],
    message: "Sensor-C2 flagged — mid-row temp 31°C",
  },
];

// IDs of all cooling edges activated in the incident
export const CRAC07_INCIDENT_EDGE_IDS = CRAC07_INCIDENT.flatMap((s) => s.edgeIds);

// All asset IDs affected (including CRAC-07)
export const CRAC07_BLAST_ASSETS = CRAC07_INCIDENT.map((s) => s.assetId);
