export interface ManualTask {
  id: string;
  title: string;
  keywords: string[];
  summary: string;
  sourceSection: string;
  steps: string[];
}

export const manualTasks: ManualTask[] = [
  {
    id: "front-panel-components",
    title: "Identify front panel components",
    keywords: [
      "front panel",
      "front ports",
      "usb front",
      "headphone jack",
      "power button",
      "sd card reader",
    ],
    summary: "Locate the front-facing ports, jacks, drive bay, and activity indicators.",
    sourceSection: "Product features > Front panel components",
    steps: [
      "Face the front of the HP EliteDesk 800 G3 SFF chassis.",
      "Identify the slim optical drive bay and optional SD card reader near the upper front area.",
      "Locate the front USB ports, including the USB Type-C charging port and the USB 3.x ports.",
      "Find the audio-out headphone jack and the combo headphone or microphone jack.",
      "Check the hard drive activity light and the power button.",
      "If the power button light flashes red, use the diagnostic LED and beep code section of the manual.",
    ],
  },
  {
    id: "rear-panel-components",
    title: "Identify rear panel components",
    keywords: [
      "rear panel",
      "rear ports",
      "displayport",
      "rj45",
      "network jack",
      "power cord connector",
    ],
    summary: "Locate the rear I/O ports, display outputs, networking, and power input.",
    sourceSection: "Product features > Rear panel components",
    steps: [
      "Face the rear of the chassis and identify the audio-in jack, audio-out jack, and optional serial port.",
      "Locate the RJ-45 network jack and the power cord connector.",
      "Identify the two standard DisplayPort connectors.",
      "Check for the optional rear port, which may be DisplayPort, HDMI, VGA, or USB-C depending on configuration.",
      "Locate the rear USB 2.0 and USB 3.x ports.",
      "If a discrete graphics card is installed, verify whether display cables should move to the add-in card instead of onboard ports.",
    ],
  },
  {
    id: "remove-access-panel",
    title: "Remove access panel",
    keywords: [
      "access panel",
      "open case",
      "open chassis",
      "remove side panel",
      "service cover",
    ],
    summary: "Safely open the chassis before internal service work.",
    sourceSection: "Removal and replacement procedures > Access panel",
    steps: [
      "Shut down the operating system, turn off the computer, and disconnect the power cord and all peripherals.",
      "If the system sits on a stand, remove it from the stand first.",
      "Slide the access panel release lever to the left until it locks.",
      "Slide the access panel toward the rear of the chassis.",
      "Lift the panel off the computer and set it aside.",
      "Before touching internal components, discharge static by touching grounded metal.",
    ],
  },
  {
    id: "remove-front-bezel",
    title: "Remove front bezel",
    keywords: [
      "front bezel",
      "remove bezel",
      "front cover",
      "bezel blank",
      "dust filter",
    ],
    summary: "Remove the front bezel to access front-drive and front-cage components.",
    sourceSection: "Removal and replacement procedures > Front bezel",
    steps: [
      "Complete standard disassembly prep and remove the access panel first.",
      "Move to the top edge of the front bezel.",
      "Lift the three bezel tabs along the top edge.",
      "Rotate the bezel outward and away from the chassis.",
      "Set the bezel aside and avoid stressing any attached filter or trim pieces.",
      "To reinstall, reverse the motion and confirm the tabs seat fully.",
    ],
  },
  {
    id: "upgrade-memory",
    title: "Upgrade or reseat DDR4 memory",
    keywords: [
      "memory",
      "ram",
      "dimm",
      "reseat memory",
      "upgrade memory",
      "dimm1",
    ],
    summary: "Remove, install, or reseat DIMMs while following slot population rules.",
    sourceSection: "Removal and replacement procedures > Memory",
    steps: [
      "Disconnect the power cord and wait about 30 seconds before touching memory modules.",
      "Remove the access panel.",
      "Open both latches on the target DIMM socket and lift the module out if removing it.",
      "For installation, align the notch in the DIMM with the tab in the socket so the module faces the correct way.",
      "Populate black DIMM sockets before white sockets, and balance capacity across Channel A and Channel B when possible.",
      "Press straight down until the module is fully seated and both latches close.",
      "Reinstall the access panel, reconnect power, and boot. System should detect memory automatically.",
    ],
  },
  {
    id: "install-expansion-card",
    title: "Remove or install expansion card",
    keywords: [
      "expansion card",
      "pcie",
      "graphics card",
      "add card",
      "remove card",
      "low profile",
    ],
    summary: "Service PCIe cards in the low-profile expansion slots.",
    sourceSection: "Removal and replacement procedures > Expansion card",
    steps: [
      "Perform disassembly prep and remove the access panel.",
      "Identify the correct PCI Express slot and matching rear slot opening.",
      "Open the slot cover retention latch by lifting the tab and rotating the latch.",
      "If removing a card, disconnect any attached cables first.",
      "For x1 cards, rock the card gently and lift straight up. For x16 cards, pull the retention arm away before lifting the card out.",
      "When installing a new card, align the bracket with the rear slot and press the card straight into the socket until fully seated.",
      "Close the retention latch and make sure any unused slot gets a cover for proper cooling.",
    ],
  },
  {
    id: "replace-3-5-drive",
    title: "Replace 3.5-inch hard drive",
    keywords: [
      "hard drive",
      "3.5 drive",
      "sata drive",
      "replace drive",
      "sata0",
      "primary drive",
    ],
    summary: "Remove or install a 3.5-inch SATA hard drive in the primary or secondary bay.",
    sourceSection: "Removal and replacement procedures > Drives",
    steps: [
      "Back up data first if removing an existing drive, then shut down, unplug power, and remove the access panel.",
      "Disconnect the power cable and SATA data cable from the rear of the drive.",
      "Pull the release lever outward, lift the rear of the drive, then slide and lift the drive out of the bay.",
      "Transfer or install the mounting screws on the replacement drive before reinstalling it.",
      "Seat the front mounting screws into the bay slots, then press the rear of the drive down until it locks.",
      "Reconnect power and SATA data. Use dark blue SATA0 for the primary drive and light blue SATA ports for secondary drives.",
      "Reassemble the chassis and boot the system.",
    ],
  },
  {
    id: "install-m2-ssd",
    title: "Install or replace M.2 SSD",
    keywords: [
      "m2",
      "ssd",
      "nvme",
      "storage card",
      "2280",
      "2230",
    ],
    summary: "Install or remove the M.2 storage card from the system board.",
    sourceSection: "Removal and replacement procedures > M.2 SSD storage card",
    steps: [
      "Shut down, unplug power, remove the access panel, and remove the front bezel.",
      "Rotate the hard drive cage upright to expose the system board storage area.",
      "Remove the screw securing the M.2 SSD.",
      "Lift the free end of the card and slide it out of the connector if removing it.",
      "For installation, insert the card into the connector at about a 30 degree angle.",
      "Press the free end down and secure it with the retaining screw.",
      "Rotate the drive cage back carefully so cables do not pinch, then reassemble the system.",
    ],
  },
  {
    id: "reset-password-jumper",
    title: "Reset password jumper",
    keywords: [
      "password jumper",
      "clear password",
      "pswd",
      "forgot bios password",
      "administrator password",
    ],
    summary: "Clear power-on and administrator passwords using the PSWD jumper.",
    sourceSection: "Password security and resetting CMOS > Resetting the password jumper",
    steps: [
      "Shut down the computer, disconnect power, and press the power button again to drain residual power.",
      "Remove the access panel and locate the green PSWD jumper on the system board.",
      "Remove the jumper from pins 1 and 2.",
      "Place the jumper on either pin 1 or pin 2 only so it does not get lost.",
      "Reinstall the access panel, reconnect power, and boot the machine fully once. This clears current passwords and disables the password feature.",
      "Shut down again, disconnect power, remove the access panel, and return the jumper to pins 1 and 2.",
      "Reassemble and reconnect external devices. Then create new passwords if needed.",
    ],
  },
  {
    id: "clear-bios-cmos",
    title: "Clear and reset BIOS CMOS",
    keywords: [
      "clear cmos",
      "reset bios",
      "cmos button",
      "factory defaults",
      "bios reset",
    ],
    summary: "Reset BIOS settings to factory defaults with the onboard CMOS button.",
    sourceSection: "Password security and resetting CMOS > Clearing and resetting the BIOS",
    steps: [
      "Turn off the computer, disconnect power, and unplug the keyboard, monitor, and other external devices.",
      "Remove the access panel and locate the CMOS button on the system board.",
      "Make sure AC power is still disconnected. The button will not clear CMOS if the power cord is attached.",
      "Press and hold the CMOS button for five seconds.",
      "Reinstall the access panel and reconnect external devices.",
      "Reconnect power and boot the computer.",
      "Expect POST messages about configuration changes, then use Computer Setup to restore date, time, and any custom BIOS settings.",
    ],
  },
  {
    id: "run-hp-hardware-diagnostics",
    title: "Run HP PC Hardware Diagnostics UEFI",
    keywords: [
      "diagnostics",
      "uefi diagnostics",
      "hardware test",
      "press f2",
      "press esc",
    ],
    summary: "Launch the built-in HP hardware diagnostics outside the operating system.",
    sourceSection: "Using HP PC Hardware Diagnostics (UEFI)",
    steps: [
      "Turn on or restart the computer.",
      "Quickly press Esc to open the startup menu.",
      "Press F2 to open HP PC Hardware Diagnostics UEFI.",
      "Select the diagnostic test category you want to run.",
      "Follow the on-screen prompts and let the test finish.",
      "If the tool returns a 24-digit failure ID, record it for support or service follow-up.",
    ],
  },
  {
    id: "create-hp-recovery-media",
    title: "Create HP recovery media",
    keywords: [
      "recovery media",
      "hp recovery manager",
      "usb recovery",
      "recovery partition",
      "factory recovery",
    ],
    summary: "Create official HP recovery media for OS restoration and hard drive replacement scenarios.",
    sourceSection: "Backing up, restoring, and recovering > Creating HP Recovery media",
    steps: [
      "Confirm the system shows both the Windows partition and Recovery partition in This PC if possible.",
      "Connect the computer to AC power before starting.",
      "Open HP Recovery Manager from the taskbar search.",
      "Select Create recovery media.",
      "Use compatible blank DVD media or a high-quality USB flash drive when prompted.",
      "Follow the on-screen steps and do not interrupt the process until media creation finishes.",
      "Store the recovery media in a safe place because only one set may be allowed.",
    ],
  },
];
